name: api-tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: ESLint format check, Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd api && npm ci && npm run test:lint
        env:
          CI: true

  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Jest unit tests, Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd api && npm ci && npm run test
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: End-to-end tests, Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd api && npm ci && npm run test:e2e
        env:
          CI: true
