name: api-tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: ESLint format check, Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd api && npm ci && npm run test:lint
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: End-to-end tests, Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd api && npm ci && npm run test:e2e
        env:
          CI: true
          MONGODB_USERNAME: aerabi
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_HOST: aerabi.8vndv.mongodb.net
          MONGODB_DATABASE: aerabi-api-ci-e2e
          MONGODB_CLOUD: true
